default:
  image: smedbergm/advent2020:0.1.1
  timeout: 5m

stages:
  - build
  - test
  - challenge

cache:
  paths:
    - advent/target/debug/deps

build-job:
  stage: build
  script:
    - pushd advent
    - cargo build --bins

test-job:
  stage: test
  script:
    - pushd advent
    - cargo test

challenge-job:
  stage: challenge
  only:
    refs:
      - master
      - beta

  script:
    - pushd /opt
    - git clone https://gitlab+deploy-token-289310:${GITLAB_SECRET_TOKEN_289310}@gitlab.com/matthew.smedberg/advent-of-code-2020-secret.git
    - popd
    - pushd advent
    - cargo build --release --bin day0
    - cat /opt/advent-of-code-2020-secret/day0/challenge target/release/day0
