default:
  image: smedbergm/advent2020:0.1.1
  timeout: 15m

stages:
  - build
  - test
  - challenge

cache:
  paths:
    - advent/target/debug/deps

build-job:
  stage: build
  script:
    - pushd advent
    - cargo build --bins

test-job:
  stage: test
  script:
    - pushd advent
    - cargo test

challenge-job:
  stage: challenge
  only:
    refs:
      - master
      - beta
  
  cache:
    key: release
    paths:
      - advent/target/release/deps

  script:
    - pushd /opt
    - git clone https://gitlab+deploy-token-289310:${GITLAB_SECRET_TOKEN_289310}@gitlab.com/matthew.smedberg/advent-of-code-2020-secret.git
    - popd
    - scripts/challenge.py
