default:
  image: smedbergm/advent2020:0.1.0

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pwd
    - ls -al .

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - export LOCAL_VARIABLE=foo
    - echo The value of LOCAL_VARIABLE is $LOCAL_VARIABLE

test-job2:
  stage: test
  script:
    - mkdir -p /opt/challenges
    - pushd /opt/challenges
    - git clone https://gitlab+deploy-token-289310:${GITLAB_SECRET_TOKEN_289310}@gitlab.com/matthew.smedberg/advent-of-code-2020-secret.git
    - popd
    - cat /opt/challenges/advent-of-code-2020-secret/day0/challenge

